# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloWord' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '3.2.1'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Masonry', '~>1.1.0'

  # Pods for HelloWord

  target 'HelloWordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HelloWordUITests' do
    # Pods for testing
  end

end
